/**
 * Neural board evaluator for Miro TCG.
 *
 * Phase 3.3 of the TCN improvement plan. Replaces (or augments) the
 * hand-coded ordinal weights in ai.ts with a small MLP that learns from
 * self-play data. The current heuristic system in ai.ts gets us strong
 * baseline play; this module is the upgrade path toward AlphaZero-style
 * learned evaluation.
 *
 * Design
 * ------
 * 1. **Feature extraction** (`extractFeatures`) — flattens a GameState into
 *    a fixed-length vector of ~80 normalized scalars (life totals, mana,
 *    hand sizes, board minion stats summed/maxed, hero classes one-hot,
 *    turn count, fatigue counters, etc.). All features are designed to be
 *    in [-1, 1] or [0, 1] so the MLP doesn't need batch norm.
 *
 * 2. **Inference** (`neuralEvaluate`) — runs a 3-layer MLP forward pass in
 *    pure TS (no external deps) producing a single scalar in [0, 1] that
 *    represents the predicted win probability for the perspective player.
 *
 * 3. **Weights** — loaded from `data/neural-eval-weights.json`. The file
 *    is generated by `scripts/train_neural_eval.py` using PyTorch (which
 *    is already a dep of the sibling card-grader project). If the file is
 *    missing or malformed, `isNeuralAvailable()` returns false and callers
 *    should fall back to the heuristic evaluator in ai.ts.
 *
 * 4. **Integration** — ai.ts can call `neuralEvaluate()` from inside its
 *    existing `evaluatePosition()` function, blending the neural value
 *    with heuristics via `AI_NEURAL_BLEND` env var (0..1, default 0).
 *    Setting it to 1 means "trust the neural net entirely"; 0 means
 *    "ignore the neural net" (current behavior).
 *
 * Why a small MLP and not a transformer
 * --------------------------------------
 * The full game state is small (two players × 7 board slots × small set
 * of features). A 64→32→1 MLP has ~5K params and runs in <1ms. We don't
 * need a transformer's sequence handling; a flat feature vector + MLP is
 * the right size for the problem. Larger models can come later if we
 * actually run into capacity limits.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import type { GameState, BoardMinion, PlayerState, HeroClass } from '../shared/types.js';

// ── Configuration ──────────────────────────────────────────────────────

/** Total number of features the extractor produces. Must match the input
 * dimension of the trained network in neural-eval-weights.json. */
export const FEATURE_DIM = 80;

const HERO_CLASSES: HeroClass[] = ['JIMMY', 'LUCAS', 'DES', 'MARI', 'KAI', 'NOVA', 'SAGE', 'REI', 'ZEN'];

const NEURAL_BLEND = parseFloat(process.env.AI_NEURAL_BLEND ?? '0');

// ── Weights loading ────────────────────────────────────────────────────

interface NeuralWeights {
  /** Schema version for forward-compat. Bumped when feature extractor changes. */
  version: number;
  /** Trained-on date in ISO format, for diagnostics. */
  generatedAt: string;
  /** Number of self-play games the model was trained on. */
  trainedGames: number;
  /** [hidden1×input] weight matrix for the first dense layer. */
  W1: number[][];
  /** [hidden1] bias vector for the first layer. */
  b1: number[];
  /** [hidden2×hidden1] weight matrix for the second dense layer. */
  W2: number[][];
  /** [hidden2] bias vector for the second layer. */
  b2: number[];
  /** [1×hidden2] output projection. */
  W3: number[][];
  /** [1] output bias. */
  b3: number[];
}

let weights: NeuralWeights | null = null;

try {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const weightsPath = path.join(__dirname, '..', 'data', 'neural-eval-weights.json');
  if (fs.existsSync(weightsPath)) {
    const raw = JSON.parse(fs.readFileSync(weightsPath, 'utf-8')) as NeuralWeights;
    if (raw.W1 && raw.W1[0]?.length === FEATURE_DIM) {
      weights = raw;
      console.log(
        `[AI-NEURAL] Loaded weights v${raw.version} ` +
          `(${raw.trainedGames} games, generated ${raw.generatedAt})`
      );
    } else {
      console.warn(
        `[AI-NEURAL] Weights file present but input dim mismatch ` +
          `(expected ${FEATURE_DIM}, got ${raw.W1?.[0]?.length}). Ignoring.`
      );
    }
  }
} catch (e) {
  console.warn('[AI-NEURAL] Failed to load weights:', e);
}

/** Returns true iff the neural evaluator is loaded and ready. Callers
 * should fall back to heuristic evaluation when this returns false. */
export function isNeuralAvailable(): boolean {
  return weights !== null && NEURAL_BLEND > 0;
}

/** Reload weights from disk — used by training loops that swap weights
 * between epochs without restarting the server. */
export function reloadNeuralWeights(): void {
  try {
    const __dir = path.dirname(fileURLToPath(import.meta.url));
    const weightsPath = path.join(__dir, '..', 'data', 'neural-eval-weights.json');
    if (fs.existsSync(weightsPath)) {
      weights = JSON.parse(fs.readFileSync(weightsPath, 'utf-8'));
      console.log('[AI-NEURAL] Reloaded weights');
    }
  } catch {
    // Keep existing weights
  }
}

// ── Feature extraction ─────────────────────────────────────────────────

/**
 * Convert a game state into a flat feature vector that the MLP can consume.
 *
 * Layout (FEATURE_DIM = 80):
 *   [0..29]   30 features for the perspective player
 *   [30..59]  30 features for the opponent
 *   [60..79]  20 global / asymmetric features (turn, mana diff, hero matchup, etc.)
 *
 * Per-player features:
 *   life / 30, max_health / 40, mana / 10, max_mana / 10, hand_size / 10,
 *   deck_size / 30, fatigue / 10, weapon_attack / 10, weapon_durability / 5,
 *   board_count / 7, sum_attack / 50, sum_health / 50, max_attack / 15,
 *   max_health_minion / 15, has_taunt (0/1), num_taunts / 7, has_divine_shield,
 *   num_divine_shields / 7, has_stealth, num_stealths / 7, has_frozen,
 *   num_frozen / 7, hero_class one-hot (9 dims summed into 9 slots)
 *
 * If the per-player block isn't full (e.g. hero class enum grows), trailing
 * zeros pad it.
 */
export function extractFeatures(state: GameState, perspectivePlayerId: string): number[] {
  const features = new Array<number>(FEATURE_DIM).fill(0);

  const me = state.players.find((p) => p.id === perspectivePlayerId);
  const opp = state.players.find((p) => p.id !== perspectivePlayerId);

  if (!me || !opp) return features;

  fillPlayerBlock(features, 0, me);
  fillPlayerBlock(features, 30, opp);

  // ── Global features ────────────────────────────────────────────────
  features[60] = clamp01((state.turn ?? 0) / 30); // turn count
  features[61] = clamp((me.mana - opp.mana) / 10, -1, 1); // mana advantage
  features[62] = clamp((me.life - opp.life) / 30, -1, 1); // life advantage
  features[63] = clamp((me.handSize() - opp.handSize()) / 10, -1, 1); // card advantage proxy
  features[64] = clamp01(me.deckSize() / 30); // my deck remaining
  features[65] = clamp01(opp.deckSize() / 30); // opp deck remaining
  features[66] = me.id === state.activePlayerId ? 1 : 0; // is it my turn
  features[67] = state.players[0].id === me.id ? 1 : 0; // first player

  // Hero matchup one-hot (compress: my class index * 9 + opp class index, scaled)
  const myCls = HERO_CLASSES.indexOf(me.hero?.class as HeroClass);
  const oppCls = HERO_CLASSES.indexOf(opp.hero?.class as HeroClass);
  if (myCls >= 0) features[68 + Math.min(myCls, 8)] = 1;
  // [68..76] my class one-hot
  // [77..78] reserved for board parity / symmetry features (left zero for now)
  features[77] = clamp((boardMinionCount(me) - boardMinionCount(opp)) / 7, -1, 1);
  features[78] = clamp((sumBoardAttack(me) - sumBoardAttack(opp)) / 30, -1, 1);
  features[79] = clamp01(state.turn ? Math.min(state.turn, 30) / 30 : 0); // late-game indicator

  return features;
}

/** Fill 30 contiguous feature slots starting at `offset` with player stats. */
function fillPlayerBlock(features: number[], offset: number, p: PlayerState): void {
  features[offset + 0] = clamp01(p.life / 30);
  features[offset + 1] = clamp01((p.maxHealth ?? 30) / 40);
  features[offset + 2] = clamp01((p.mana ?? 0) / 10);
  features[offset + 3] = clamp01((p.maxMana ?? 0) / 10);
  features[offset + 4] = clamp01(p.handSize() / 10);
  features[offset + 5] = clamp01(p.deckSize() / 30);
  features[offset + 6] = clamp01((p.fatigue ?? 0) / 10);
  features[offset + 7] = clamp01((p.weapon?.attack ?? 0) / 10);
  features[offset + 8] = clamp01((p.weapon?.durability ?? 0) / 5);

  const board = p.board ?? [];
  features[offset + 9] = clamp01(board.length / 7);
  features[offset + 10] = clamp01(sumBoardAttack(p) / 50);
  features[offset + 11] = clamp01(sumBoardHealth(p) / 50);
  features[offset + 12] = clamp01(maxStat(board, 'attack') / 15);
  features[offset + 13] = clamp01(maxStat(board, 'health') / 15);

  const taunts = board.filter((m) => hasKeyword(m, 'TAUNT'));
  features[offset + 14] = taunts.length > 0 ? 1 : 0;
  features[offset + 15] = clamp01(taunts.length / 7);

  const shielded = board.filter((m) => hasKeyword(m, 'DIVINE_SHIELD'));
  features[offset + 16] = shielded.length > 0 ? 1 : 0;
  features[offset + 17] = clamp01(shielded.length / 7);

  const stealths = board.filter((m) => hasKeyword(m, 'STEALTH'));
  features[offset + 18] = stealths.length > 0 ? 1 : 0;
  features[offset + 19] = clamp01(stealths.length / 7);

  const frozen = board.filter((m) => hasKeyword(m, 'FROZEN'));
  features[offset + 20] = frozen.length > 0 ? 1 : 0;
  features[offset + 21] = clamp01(frozen.length / 7);

  // Hero class one-hot in features[offset+22 .. offset+30]
  const cls = HERO_CLASSES.indexOf(p.hero?.class as HeroClass);
  if (cls >= 0 && cls < 8) {
    features[offset + 22 + cls] = 1;
  }
}

// ── Forward pass ───────────────────────────────────────────────────────

/**
 * Run the MLP forward pass on a feature vector. ReLU on the two hidden
 * layers, sigmoid on the output. Returns a scalar in [0, 1] interpreted
 * as the perspective player's win probability.
 *
 * Throws if weights aren't loaded — callers should gate on isNeuralAvailable().
 */
export function neuralForward(features: number[]): number {
  if (!weights) {
    throw new Error('Neural weights not loaded — call isNeuralAvailable() first');
  }
  const h1 = relu(matVecAdd(weights.W1, features, weights.b1));
  const h2 = relu(matVecAdd(weights.W2, h1, weights.b2));
  const out = matVecAdd(weights.W3, h2, weights.b3)[0];
  return sigmoid(out);
}

/**
 * Public entry point. Extract features from `state` and run the network.
 * Returns the predicted win probability for `perspectivePlayerId` in [0, 1],
 * or null if neural eval is disabled or weights are missing.
 */
export function neuralEvaluate(
  state: GameState,
  perspectivePlayerId: string
): number | null {
  if (!isNeuralAvailable()) return null;
  const features = extractFeatures(state, perspectivePlayerId);
  return neuralForward(features);
}

/**
 * Blend the neural and heuristic evaluations using AI_NEURAL_BLEND.
 * Returns `heuristicValue` unchanged when neural eval is unavailable
 * or AI_NEURAL_BLEND is 0, so callers can drop this in without
 * conditionals.
 *
 * `heuristicValue` should already be normalized to roughly [0, 1] for
 * the blend to be meaningful.
 */
export function blendEval(
  state: GameState,
  perspectivePlayerId: string,
  heuristicValue: number
): number {
  const neural = neuralEvaluate(state, perspectivePlayerId);
  if (neural === null) return heuristicValue;
  return heuristicValue * (1 - NEURAL_BLEND) + neural * NEURAL_BLEND;
}

// ── Numerical helpers ──────────────────────────────────────────────────

function relu(v: number[]): number[] {
  return v.map((x) => (x > 0 ? x : 0));
}

function sigmoid(x: number): number {
  // Clamp input to avoid Math.exp overflow on extreme values
  if (x > 30) return 1;
  if (x < -30) return 0;
  return 1 / (1 + Math.exp(-x));
}

function matVecAdd(W: number[][], v: number[], b: number[]): number[] {
  const out = new Array<number>(W.length).fill(0);
  for (let i = 0; i < W.length; i++) {
    let sum = b[i];
    const row = W[i];
    for (let j = 0; j < row.length; j++) {
      sum += row[j] * v[j];
    }
    out[i] = sum;
  }
  return out;
}

function clamp(x: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, x));
}

function clamp01(x: number): number {
  return clamp(x, 0, 1);
}

// ── Game-state helpers (defensive — don't crash on partial states) ─────

function boardMinionCount(p: PlayerState): number {
  return (p.board ?? []).length;
}

function sumBoardAttack(p: PlayerState): number {
  return (p.board ?? []).reduce((s, m) => s + (m.attack ?? 0), 0);
}

function sumBoardHealth(p: PlayerState): number {
  return (p.board ?? []).reduce((s, m) => s + (m.health ?? 0), 0);
}

function maxStat(board: BoardMinion[], key: 'attack' | 'health'): number {
  let max = 0;
  for (const m of board) {
    const v = (m as Record<string, unknown>)[key];
    if (typeof v === 'number' && v > max) max = v;
  }
  return max;
}

function hasKeyword(minion: BoardMinion, keyword: string): boolean {
  // Defensive: keywords might be a Set, array, or undefined depending on
  // how the engine has serialized this minion.
  const k = (minion as Record<string, unknown>).keywords;
  if (!k) return false;
  if (Array.isArray(k)) return k.includes(keyword);
  if (k instanceof Set) return k.has(keyword);
  return false;
}
