// Generated by scripts/animated-art/generate.py — do not edit by hand.
// cardCodes listed here have /cards/anims/{cardCode}.webm available.
// CardArt renders the WebM loop in golden mode when this Set contains
// the cardCode; otherwise the static PNG is used (gold overlay still
// applies — just no motion within the art).
export const CARD_ART_ANIMS = new Set<string>([
  "DRK032",
  "JIM022",
]);
